#! /bin/bash

#АВТОСТАРТ
sxhkd &
xfce4-power-manager &
nm-applet &
redshift-gtk &
numlockx &
nitrogen --restore &
polybar example &
polybar top &
picom --experimental-backend &
xsetroot -cursor_name left_ptr &
## Polkit authenication
(sleep 2s && /usr/lib/mate-polkit/polkit-mate-authentication-agent-1) &
#viber &
whatsapp-for-linux &
telegram-desktop &
#subl &
#firefox &
setxkbmap -layout 'us,ru' -option 'grp:ctrl_shift_toggle' &
#kdeconnect-indicator &

#ВОРКСПЕЙСЫ
bspc monitor HDMI-1 -d          
bspc monitor HDMI-2 -d        

#РАМКИ И ГАПСЫ
#bspc config border_width         1
bspc config window_gap          5

bspc config normal_border_color "#23252e"
bspc config active_border_color "#23252e"
bspc config focused_border_color "#f9f8fe"

#ЦВЕТ ПРОСТРАНСТВА ПРИ ВЫБОРЕ ПОЛОЖЕНИЯ НОВОГО ОКНА
bspc config presel_feedback_color "fd2e59"

#ПРИ ПОМОЩИ ЭТОЙ ХРЕНИ МОЖНО СДЕЛАТЬ ГАПСЫ ТОЛЬКО МЕЖДУ ОКНАМИ
#bspc config window_gap $gap;
#bspc config top_padding -$(($gap+2))
#bspc config left_padding -$(($gap+2))
#bspc config right_padding -$(($gap+4))
#bspc config bottom_padding $(($PANEL_HEIGHT-$gap))



#КОФИЦИЕНТ РАЗДЕЛЕНИЯ, СКОЛЬКО ПРОЦЕНТОВ ОСТАНЕТСЯ ОТ РОДИТЕЛЬСКОГО ОКНА ПРИ ОТКРЫТИИ НОВОГО
bspc config split_ratio          0.5
#ФОКУС ОКНА НАВЕДЕНИЕМ КУРСОРА
bspc config focus_follows_pointer false
bspc config pointer_modifier	super

#РЕЖИМ МОНОКЛЯ КОГДА ОТКРЫТО ОДНО ОКНО
bspc config single_monocle	     false

#ОТКЛЮЧЕНИЕ ГАПСОВ РАМОК И ОТСТУПОВ КОГДА ОТКРЫТО ОДНО ОКНО
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true


#СХЕМЫ СОГЛАСНО КОТОРЫМ БУДУТ ОТКРЫВАТСЯ ОКНА
#bspc config automatic_scheme	spiral


#ПРАВИЛА ОКОН
# xprop grep WM_CLASS в терминале и левый клик на приложение
bspc rule -a firefox follow=off rectangle=1350x900+50+90 desktop='^1'
#bspc rule -a TelegramDesktop state=floating follow=off desktop='^7'
#bspc rule -a firefox desktop='^1'
bspc rule -a Subl3 desktop='^3'
bspc rule -a ViberPC desktop='^7'
bspc rule -a Virt-manager desktop='^6'
bspc rule -a "VirtualBox Manager" follow=on center=on desktop='^6'
bspc rule -a TelegramDesktop  desktop='^8'
bspc rule -a mpv state=floating rectangle=800x450+560+315 follow=off
bspc rule -a dmenu rectangle=900x22+610+90
bspc rule -a Media viewer rectangle=1350x900+285+90 state=floating
bspc rule -a Inkscape desktop='^4'
#bspc rule -a Blender state=floating follow=off desktop='^2'
bspc rule -a xfreerdp desktop=w follow=on state=tiled
bspc rule -a org.remmina.Remmina state=floating rectangle=800x600+560+315 follow=off
bspc rule -a "KeePassXC" state=floating follow=off center=on
bspc rule -a "TeamViewer" state=floating follow=off center=on
bspc rule -a "Lxappearance" state=floating rectangle=1050x750
bspc rule -a "qt5ct" state=floating 
bspc rule -a "Whatsapp-for-linux" desktop='^7'
#bspc rule -a Nitrogen state=floating
bspc rule -a Galculator state=floating follow=off
bspc rule -a simplescreenrecorder state=floating follow=off center=on